version: "3.3"

services:
  server:
    image: nginx:1.17-alpine
    ports:
      - 8088:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/public:/usr/share/nginx/html/
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    image: joseluisq/php:fpm-7.4
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=128M"
      - "PHP_FPM_LISTEN=9090"
    expose:
      - "9090"
    volumes:
      - ./nginx/public:/usr/share/nginx/html/
