name: devel-8.0
on:
  pull_request:
    branches:
      - master
    paths:
      - 8.0-fpm/**
  push:
    branches:
      - master
    paths:
      - 8.0-fpm/**

jobs:
  php:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build:
          - amd64
          - "386"
          - arm64
          - armv7
          - armv6
        include:
          - build: amd64
            arch: linux/amd64
          - build: "386"
            arch: linux/386
          - build: arm64
            arch: linux/arm64
          - build: armv6
            arch: linux/arm/v6
          - build: armv7
            arch: linux/arm/v7
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: 8.0-fpm-${{ matrix.arch }}-buildx-${{ github.sha }}
          restore-keys: |
            8.0-fpm-${{ matrix.arch }}-buildx-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and Test
        uses: docker/build-push-action@v3
        with:
          push: false
          context: .
          platforms: ${{ matrix.arch }}
          file: 8.0-fpm/Dockerfile
          tags: joseluisq/php-fpm:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
